// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EBookkeepingAuth.Data.CompanyContext
{
    public partial class Companies
    {
        public Companies()
        {
            CompanyAssociation = new HashSet<CompanyAssociation>();
        }

        public Guid Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTin { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string GhPostGps { get; set; }
        public string BusinessRegistrationNumber { get; set; }
        public string PostalAddress { get; set; }
        public string City { get; set; }
        public Guid TransactionCurrency { get; set; }
        public Guid UserId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Status { get; set; }

        public virtual ICollection<CompanyAssociation> CompanyAssociation { get; set; }
    }
}