// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EBookkeepingAuth.Data.CompanyContext
{
    public partial class CompanyAssociation
    {
        public Guid Id { get; set; }
        public Guid CompanyId { get; set; }
        public string AssociatedUserId { get; set; }
        public string Status { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public string UserId { get; set; }
        public bool? IsAdmin { get; set; }

        public virtual Companies Company { get; set; }
        public virtual AspNetUsers User { get; set; }
    }
}